### ISSUE TITLE
Not showing in tabs after install (A1111)

### ISSUE THREAD

**Issue by LindezaBlue** [MackinationsAi/sd-webui-udav2#12]
I installed this via direct install within the A1111 extension loader.

![{C7AD9DE2-DA4B-41DE-BBF2-3BB0DDBD5544}](https://github.com/user-attachments/assets/7608d81b-6364-49b3-8106-ab992f579527)

This is my tab bar... nothing shows. 
![{E5BCF560-D740-45D1-BAC4-29C76C32C7F4}](https://github.com/user-attachments/assets/f18d6883-75c9-4621-bff6-413b9da10e44)

Did I miss anything during the installation process?

**Comment by Cigoler** [comment]
Check your terminal, there's probably an error.

For me I had to update the python file `upgraded_depth_anything_v2.py` (which you can find in the extensions folder: ForgeFlux\webui\extensions\sd-forge-udav2\scripts) and change two lines to use type="filepath" instead of "file":

on line 268:
`input_images = gr.Files(label="Upload Images", type="filepath", elem_id="img-display-input")`

And on line 318:
`input_videos = gr.Files(label="Input Videos", type="filepath", elem_id='img-display-input')`

But I notice you're not using forge, so your mileage may vary - I'm sure there's an error in your terminal that will point to the problem though.

**Comment by LindezaBlue** [comment]
Shouldn't matter if I use Forge or A1111, they both run on the same backend with some slight changes.
No errors show up in console in A1111 or Forge.

**Comment by MackinationsAi** [comment]
Error happens bc the code was updated for gradio>=5.0.0 - [similar_resolved_issue](https://github.com/MackinationsAi/sd-webui-udav2/issues/11#issuecomment-2463180391) as Cigoler mentinoed above, this is the change that is most likely preventing the extension for loading in your tabs - [commit-c98facb](https://github.com/MackinationsAi/sd-webui-udav2/commit/5df351da162b21285929ad722f9718f431fadfee). If that doesn't fix the issue, let me know & I will help you troubleshoot to get it back up & running for you.

**Comment by LindezaBlue** [comment]
Ahh! That would make sense I don't use forge atm since I get some massive memory leaks in RAM. Not even sure if there is going to be an update for A1111 >_>
