### ISSUE TITLE
something wrong？

### ISSUE THREAD

**Issue by AdamShuo** [MackinationsAi/sd-webui-udav2#7]
F:\ProgramData\sd-webui-aki-v4.4>git clone https://github.com/MackinationsAi/sd-webui-udav2
Cloning into 'sd-webui-udav2'...
fatal: unable to access 'http://github.com/MackinationsAi/sd-webui-udav2.git/': Empty reply from server

**Comment by MackinationsAi** [comment]
![Screenshot 2024-08-19 015308](https://github.com/user-attachments/assets/77f4bf82-7a5c-4a36-8c0c-12cd3bc8fa9d)

Just tried & it cloned just fine? When is the last time you updated git on your machine?

**Comment by MackinationsAi** [comment]
Were you able to clone the extension? If not you can always install it directly from inside a1111's extensions tab as it is included in the index.json, or if you're trying to use the extension w/ forge you can download the forge version .zip or .7z found here [sd-forge-udav2_v0.0.5](https://github.com/MackinationsAi/sd-webui-udav2/releases/tag/sd-forge-udav2_v0.0.5).

If none of those options work, you can always download the extension files manually one-by-one [just make sure you place everything in the correct folders|location-structure w/ the right names otherwise the extension will not work properly].

Finally, if you would prefer to use UDAV2 as a stand-alone app, you can. Found [here](https://github.com/MackinationsAi/Upgraded-Depth-Anything-V2).
